export {
  MAX_PROJECTION_GENERATION_REFERENCES,
  MAX_PROJECTION_SELECTED_ROOT_FACTS,
  MAX_PROJECTION_UNSETTLED_TARGETS,
  SELECTION_PROJECTION_VERSION,
  SelectionProjectionError,
  createAuthenticatedProjectionEvidence,
  nextProjectionEpoch,
  selectionTargetKey,
  unsettledTargetsForSelection,
  type ArtifactShapeProof,
  type AuthenticatedGenerationReference,
  type AuthenticatedProjectionEvidence,
  type DiscoveryState,
  type LayoutBasisProof,
  type ProjectedDirectoryAnchor,
  type ProjectedFileFact,
  type ProjectionEpoch,
  type ProjectionMetrics,
  type ProjectionTraceEvent,
  type ProjectionTraceSource,
  type RetryableDiscoveryReason,
  type SelectedRootFact,
  type SelectionProjectionEvent,
  type SelectionProjectionState,
  type SelectionProjectionV1,
  type SettledLayoutBasisProof,
  type UnsettledSelectionTarget,
} from './model'
export {
  SelectionProjectionController,
  createSelectionProjectionState,
  reduceSelectionProjection,
} from './reducer'
export {
  RetryableProjectionDiscoveryError,
  discoverAuthenticatedSelection,
  retryAuthenticatedSelectionDiscovery,
  type AuthenticatedDiscoveryCompletion,
  type AuthenticatedDiscoveryRequest,
  type AuthenticatedDiscoverySource,
} from './coordinator'
