package transfer

import (
	"crypto/sha256"
	"encoding/binary"

	"github.com/windshare/windshare/core/catalog"
)

const directoryAdmissionTokenBytes = sha256.Size

// Directory admission keys are generated by an output session and never leave
// the backend.  Keeping the key outside DirectoryAdmission means a caller can
// carry/compare a token but cannot deterministically manufacture one that the
// session will accept.
const directoryAdmissionSecretBytes = sha256.Size

// DirectoryAdmission is an opaque proof that an output session accepted one
// committed directory generation. Callers can compare or carry it, but cannot
// alter its binding fields. A file must carry the exact parent token returned by
// AdmitDirectory; path strings alone are never sufficient authority.
type DirectoryAdmission struct {
	token      [directoryAdmissionTokenBytes]byte
	directory  catalog.DirectoryID
	generation catalog.DirectoryGeneration
	parent     [directoryAdmissionTokenBytes]byte
	path       string
	modified   catalog.ModifiedTime
}

func (admission DirectoryAdmission) IsZero() bool {
	return admission.token == [directoryAdmissionTokenBytes]byte{}
}
func (admission DirectoryAdmission) Bytes() []byte                    { return append([]byte(nil), admission.token[:]...) }
func (admission DirectoryAdmission) DirectoryID() catalog.DirectoryID { return admission.directory }
func (admission DirectoryAdmission) Generation() catalog.DirectoryGeneration {
	return admission.generation
}
func (admission DirectoryAdmission) Path() string { return admission.path }
func (admission DirectoryAdmission) Parent() DirectoryAdmission {
	if admission.IsZero() || admission.parent == ([directoryAdmissionTokenBytes]byte{}) {
		return DirectoryAdmission{}
	}
	return DirectoryAdmission{token: admission.parent}
}
func (admission DirectoryAdmission) Equal(other DirectoryAdmission) bool {
	return admission.token == other.token
}

func validateOutputDirectory(directory OutputDirectory) error {
	if directory.DirectoryID.IsZero() || directory.Generation.IsZero() ||
		(directory.Path == "" && !directory.ParentAdmission.IsZero()) {
		return ErrInvalidDirectoryAdmission
	}
	if directory.Path != "" {
		canonical, err := catalog.CanonicalPath(directory.Path)
		if err != nil || canonical != directory.Path {
			return ErrInvalidDirectoryAdmission
		}
	}
	if directory.Path != "" && directory.ParentAdmission.IsZero() {
		return ErrInvalidDirectoryAdmission
	}
	return nil
}

// NewDirectoryAdmissionWithSecret mints a backend-scoped admission proof.  The
// secret is intentionally supplied by the output session rather than derived
// from caller-visible directory fields; this prevents a forged token from being
// accepted merely because it has the same path and generation.  Backends should
// retain the secret only for the lifetime of their session and use the exact
// returned value for idempotent retries.
func NewDirectoryAdmissionWithSecret(secret []byte, directory OutputDirectory) (DirectoryAdmission, error) {
	if len(secret) != directoryAdmissionSecretBytes {
		return DirectoryAdmission{}, ErrInvalidDirectoryAdmission
	}
	if err := validateOutputDirectory(directory); err != nil {
		return DirectoryAdmission{}, err
	}
	hash := sha256.New()
	_, _ = hash.Write([]byte("windshare/directory-admission/session-v1\x00"))
	_, _ = hash.Write(secret)
	_, _ = hash.Write(directory.DirectoryID.Bytes())
	_, _ = hash.Write(directory.Generation.Bytes())
	_, _ = hash.Write([]byte(directory.Path))
	writeDirectoryAdmissionModifiedTime(hash, directory.ModifiedTime)
	if !directory.ParentAdmission.IsZero() {
		_, _ = hash.Write(directory.ParentAdmission.token[:])
	}
	var token [directoryAdmissionTokenBytes]byte
	copy(token[:], hash.Sum(nil))
	return DirectoryAdmission{
		token: token, directory: directory.DirectoryID, generation: directory.Generation,
		parent: directory.ParentAdmission.token, path: directory.Path, modified: directory.ModifiedTime,
	}, nil
}

func admissionMatchesDirectory(admission DirectoryAdmission, directory OutputDirectory) bool {
	if admission.IsZero() || validateOutputDirectory(directory) != nil {
		return false
	}
	return admission.directory == directory.DirectoryID && admission.generation == directory.Generation &&
		admission.path == directory.Path && admission.parent == directory.ParentAdmission.token &&
		admission.modified == directory.ModifiedTime
}

// ValidateDirectoryAdmissionBinding lets a backend validate a token returned by
// its own admission ledger without exposing token construction to callers.
func ValidateDirectoryAdmissionBinding(admission DirectoryAdmission, directory OutputDirectory) error {
	if !admissionMatchesDirectory(admission, directory) {
		return ErrDirectoryAdmissionMismatch
	}
	return nil
}

func writeDirectoryAdmissionModifiedTime(hash interface{ Write([]byte) (int, error) }, modified catalog.ModifiedTime) {
	present := byte(0)
	if modified.Present() {
		present = 1
	}
	_, _ = hash.Write([]byte{present})
	var seconds [8]byte
	binary.BigEndian.PutUint64(seconds[:], uint64(modified.Seconds()))
	_, _ = hash.Write(seconds[:])
	var nanoseconds [4]byte
	binary.BigEndian.PutUint32(nanoseconds[:], modified.Nanoseconds())
	_, _ = hash.Write(nanoseconds[:])
	_, _ = hash.Write([]byte{byte(modified.Precision())})
}
