import { expect, test } from '@playwright/test'
import { capture, expectNoHorizontalOverflow, galleryEvidence as evidence, GALLERY_PATH, showScenario } from './receiver-gallery/assertions'

test.beforeEach(({ page }) => { page.on('pageerror', error => { console.error(error.stack) }) })

test('production explorer keeps semantic selection, preview focus and current task independent', async ({ page }) => {
  await page.goto(GALLERY_PATH)
  const task = page.locator('.share-workspace > .task-card')
  await expect(task).toContainText('Downloading')
  const before = await evidence(page)
  await page.getByRole('button', { name: 'Select items', exact: true }).click()
  const checkbox = page.getByRole('checkbox', { name: 'Select Summer photos', exact: true })
  await expect(checkbox).toHaveAttribute('aria-checked', 'mixed')
  await checkbox.focus()
  await page.keyboard.press('Space')
  await expect(checkbox).toBeChecked()
  expect((await evidence(page)).intents).toEqual(['toggle:photos'])
  await page.getByRole('button', { name: 'Clear selection', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Download selected', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Done selecting', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Download this folder', exact: true })).toBeDisabled()
  await expect(page.getByText('Pause the current download before starting another.', { exact: true })).toBeVisible()

  const folder = page.getByRole('button', { name: 'Summer photos', exact: true }).last()
  await folder.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Portrait.png', exact: true })).toBeVisible()
  await expect(task).toContainText('Downloading')
  const previewTrigger = page.getByRole('button', { name: 'Portrait.png', exact: true })
  await previewTrigger.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('img', { name: 'Preview of Portrait.png' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(previewTrigger).toBeFocused()

  const details = task.getByRole('button', { name: 'Details', exact: true })
  await details.click()
  await expect(page.getByRole('dialog')).toContainText('Receiving the selected content')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(details).toBeFocused()

  const downloads = page.getByRole('button', { name: /^Downloads/ })
  await downloads.click()
  await expect(page.getByRole('dialog').locator('.task-card')).toHaveCount(3)
  await expect(page.getByRole('dialog')).toContainText('Archive')
  await page.getByRole('dialog').getByRole('button', { name: 'Details', exact: true }).last().click()
  await expect(page.getByRole('dialog')).toContainText('Created')
  await page.getByRole('button', { name: 'All downloads', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Details', exact: true }).last()).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(downloads).toBeFocused()
  expect(await evidence(page)).toMatchObject({ taskId: before.taskId, taskLabel: before.taskLabel, taskBytes: before.taskBytes })
})

test('media reflows across viewports and themes while touch and keyboard actions stay usable', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
  const page = await context.newPage()
  await page.goto(GALLERY_PATH)
  await page.getByRole('button', { name: 'Next', exact: true }).tap()
  await expect(page.getByRole('navigation', { name: 'Directory pages' })).toContainText('Page 2 of 2')
  await page.getByRole('button', { name: /^Downloads/ }).tap()
  await expect(page.getByRole('dialog')).toBeVisible()
  await capture(page, 'mobile-downloads', true)
  await page.getByRole('button', { name: 'Close downloads', exact: true }).tap()
  await expect(page.locator('.share-workspace > .task-card')).toContainText('Downloading')

  // Theme transitions have their own contract; representative pairs cover media reflow.
  for (const [device, width, height, colorScheme] of [
    ['desktop', 1440, 1000, 'light'], ['tablet', 820, 1180, 'dark'], ['mobile', 390, 844, 'dark'],
  ] as const) {
    await page.setViewportSize({ width, height })
    await page.emulateMedia({ colorScheme, reducedMotion: 'reduce' })
    for (const value of ['portrait', 'landscape', 'video'] as const) {
      await showScenario(page, value)
      if (value === 'video') {
        await page.getByRole('button', { name: 'Preview a frame', exact: true }).tap()
        await expect(page.getByRole('img', { name: 'Video preview of Summer afternoon.mp4' })).toBeVisible()
        await expect(page.locator('.preview-frame-stage')).toHaveAttribute('aria-busy', 'false')
        await expect(page.getByRole('slider', { name: 'Seek Summer afternoon.mp4' })).toBeInViewport()
      } else {
        const photo = page.getByRole('img', { name: /^Preview of/ })
        await expect(photo).toBeVisible()
        await expect(photo).toHaveCSS('object-fit', 'contain')
        const box = await photo.boundingBox()
        expect(box!.width).toBeLessThanOrEqual(width)
      }
      await expectNoHorizontalOverflow(page)
      await capture(page, device + '-' + colorScheme + '-' + value, true)
    }
  }
  const seek = page.getByRole('slider', { name: 'Seek Summer afternoon.mp4' })
  await seek.focus()
  await page.keyboard.press('ArrowRight')
  expect((await evidence(page)).intents.some(intent => intent.startsWith('seek:'))).toBe(true)

  await showScenario(page, 'unsupported')
  await page.getByRole('button', { name: 'Preview', exact: true }).tap()
  await expect(page.getByRole('alert')).toBeVisible()
  const download = page.getByRole('button', { name: 'Download file', exact: true })
  await expect(download).toBeEnabled()
  await download.tap()
  expect((await evidence(page)).intents.some(intent => intent.startsWith('choose:'))).toBe(true)
  await expectNoHorizontalOverflow(page)
  await context.close()
})

test('a full catalog page keeps download controls close while every item remains reachable', async ({ page }) => {
  await page.goto(GALLERY_PATH)
  for (const [device, width, height] of [['desktop', 1440, 1000], ['mobile', 390, 844]] as const) {
    await page.setViewportSize({ width, height })
    await showScenario(page, 'full-directory')
    const contents = page.getByRole('list', { name: 'Folder contents' })
    await expect(contents.locator('.explorer-row')).toHaveCount(256)
    const download = page.getByRole('button', { name: 'Download this folder', exact: true })
    const pause = page.locator('.share-workspace > .task-card').getByRole('button', { name: 'Pause', exact: true })
    const downloadBefore = await download.boundingBox()
    const pauseBefore = await pause.boundingBox()
    expect(downloadBefore!.y + downloadBefore!.height).toBeLessThan(height)
    expect(pauseBefore!.y + pauseBefore!.height).toBeLessThan(height * 1.25)
    await contents.focus()
    await page.keyboard.press('Control+End')
    const lastItem = page.getByRole('button', { name: 'Document 256.txt', exact: true })
    await expect(lastItem).toBeInViewport()
    expect(await download.boundingBox()).toEqual(downloadBefore)
    expect(await pause.boundingBox()).toEqual(pauseBefore)
    await lastItem.click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(lastItem).toBeFocused()
    await capture(page, device + '-full-directory', true)
  }
})
