import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'

import { encodeBase64Url } from '../../src/crypto/bytes'
import {
  FILE_CHECKPOINT_CHECKSUM_DOMAIN,
  FILE_CHECKPOINT_COMMIT_CANDIDATE,
  FILE_CHECKPOINT_COMMIT_VERIFIED,
  FILE_CHECKPOINT_MAX_FILE_SIZE,
  FILE_CHECKPOINT_NAMESPACE,
  FILE_CHECKPOINT_OWNERSHIP_MARKER,
  FILE_CHECKPOINT_ORIGIN_PUBLISHED,
  FILE_CHECKPOINT_ORIGIN_RETIRING,
  FILE_CHECKPOINT_PHASE_ACTIVE,
  FILE_CHECKPOINT_PHASE_PAUSED,
  FILE_CHECKPOINT_PHASE_QUARANTINED,
  FILE_CHECKPOINT_PHASE_RETIRED,
  FILE_CHECKPOINT_QUARANTINE_FINAL_MISMATCH,
  FILE_CHECKPOINT_QUARANTINE_STAGE_UNSAFE,
  FILE_CHECKPOINT_RETIREMENT_INVALIDATED_REVISION,
  canonicalFileCheckpointBytes,
  decodeFileCheckpointOwnership,
  decodeFileCheckpointV1,
  encodeFileCheckpointOwnership,
  encodeFileCheckpointV1,
  newFileCheckpointV1,
  selectVerifiedCheckpoint,
  validateFileCheckpointTransition,
} from '../../src/output/persistence/checkpoint'

const intent = bytes(0x10, 32)
const fileId = bytes(0x20, 16)
const revision = bytes(0x30, 16)
const root = bytes(0x40, 32)
const object = bytes(0x50, 32)

describe('FileCheckpointV1', () => {
  it('round-trips the Go envelope and computes the checksum over canonical payload', () => {
    const candidate = newFileCheckpointV1({
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: ['folder', 'file.bin'],
      exactSize: 64n,
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      stateGeneration: 1n,
      checkpointGeneration: 1n,
      verifiedRanges: [{ start: 0n, end: 16n }, { start: 32n, end: 64n }],
      phase: FILE_CHECKPOINT_PHASE_ACTIVE,
      commitState: FILE_CHECKPOINT_COMMIT_CANDIDATE,
    })
    const encoded = encodeFileCheckpointV1(candidate)
    const decoded = decodeFileCheckpointV1(encoded)
    expect(decoded).toEqual(candidate)
    // Generated by the Go FileCheckpointV1 codec from the same byte identities.
    expect(candidate.recordId).toBe('kilEPt_MY8L6PxB2nW4S4s_0SpigsWUWbSTtDIimRUI')
    expect(candidate.checksum).toBe('y_FmrUwcZV-I15x_gTsX56GLw_Tz2BcA4pihgSfJZpQ')

    const payload = canonicalFileCheckpointBytes(candidate)
    const expectedChecksum = createHash('sha256')
      .update(`${FILE_CHECKPOINT_CHECKSUM_DOMAIN}\0`, 'utf8')
      .update(payload)
      .digest()
    expect(candidate.checksum).toBe(encodeBase64Url(expectedChecksum))
  })

  it('keeps immutable identity while requiring monotonic ranges and generations', () => {
    const previous = newFileCheckpointV1({
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: 'file.bin',
      exactSize: 8n,
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      stateGeneration: 1n,
      checkpointGeneration: 1n,
      verifiedRanges: [{ start: 0n, end: 4n }],
      phase: FILE_CHECKPOINT_PHASE_ACTIVE,
      commitState: FILE_CHECKPOINT_COMMIT_CANDIDATE,
    })
    const verified = newFileCheckpointV1({
      ...previous,
      stateGeneration: 1n,
      checkpointGeneration: 1n,
      verifiedRanges: previous.verifiedRanges,
      phase: FILE_CHECKPOINT_PHASE_ACTIVE,
      commitState: FILE_CHECKPOINT_COMMIT_VERIFIED,
    })
    expect(verified.recordId).toBe(previous.recordId)
    validateFileCheckpointTransition(previous, verified)
    const advanced = newFileCheckpointV1({
      ...verified,
      stateGeneration: 2n,
      checkpointGeneration: 2n,
      verifiedRanges: [{ start: 0n, end: 8n }],
      phase: FILE_CHECKPOINT_PHASE_PAUSED,
      commitState: FILE_CHECKPOINT_COMMIT_VERIFIED,
    })
    expect(() => validateFileCheckpointTransition(verified, advanced)).not.toThrow()
    expect(() => validateFileCheckpointTransition(advanced, previous)).toThrow()
  })

  it('encodes and verifies an ownership marker independently of file ranges', () => {
    const encoded = encodeFileCheckpointOwnership({
      marker: FILE_CHECKPOINT_OWNERSHIP_MARKER,
      namespace: FILE_CHECKPOINT_NAMESPACE,
      backend: 'test/native',
      rootIdentity: encodeBase64Url(root),
    })
    expect(decodeFileCheckpointOwnership(encoded)).toEqual({
      marker: FILE_CHECKPOINT_OWNERSHIP_MARKER,
      namespace: FILE_CHECKPOINT_NAMESPACE,
      backend: 'test/native',
      rootIdentity: encodeBase64Url(root),
    })
    encoded[encoded.length - 1] = (encoded.at(-1) ?? 0) ^ 1
    expect(() => decodeFileCheckpointOwnership(encoded)).toThrow(/checksum/u)
  })

  it('rejects overlapping and adjacent ranges instead of repairing persisted records', () => {
    const base = {
      transferIntentDigest: encodeBase64Url(intent),
      fileId: encodeBase64Url(fileId),
      fileRevision: encodeBase64Url(revision),
      canonicalPath: 'file.bin',
      exactSize: 16n,
      backend: 'test/native',
      rootIdentity: encodeBase64Url(root),
      ownedOutputObject: encodeBase64Url(object),
      stateGeneration: 1n,
      checkpointGeneration: 1n,
    } as const
    expect(() => newFileCheckpointV1({ ...base, verifiedRanges: [{ start: 0n, end: 8n }, { start: 8n, end: 12n }] })).toThrow()
    expect(() => newFileCheckpointV1({ ...base, verifiedRanges: [{ start: 0n, end: 8n }, { start: 4n, end: 12n }] })).toThrow()
  })

  it('fails closed when committed records disagree at one generation', () => {
    const base = {
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: 'file.bin',
      exactSize: 16n,
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      checkpointGeneration: 1n,
      phase: FILE_CHECKPOINT_PHASE_ACTIVE,
      commitState: FILE_CHECKPOINT_COMMIT_VERIFIED,
    } as const
    const first = newFileCheckpointV1({ ...base, stateGeneration: 1n, verifiedRanges: [{ start: 0n, end: 4n }] })
    const conflicting = newFileCheckpointV1({ ...base, stateGeneration: 2n, verifiedRanges: [{ start: 0n, end: 8n }] })
    expect(() => selectVerifiedCheckpoint(first, conflicting)).toThrow(/disagree/u)
    const anotherRoot = newFileCheckpointV1({
      ...base,
      rootIdentity: bytes(0x60, 32),
      stateGeneration: 2n,
      checkpointGeneration: 2n,
      verifiedRanges: [{ start: 0n, end: 8n }],
    })
    expect(() => selectVerifiedCheckpoint(first, anotherRoot)).toThrow(/identity/u)
  })

  it('uses Go catalog size and backend-text limits', () => {
    const base = {
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: 'file.bin',
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      stateGeneration: 1n,
      checkpointGeneration: 1n,
      verifiedRanges: [],
    } as const
    expect(() => newFileCheckpointV1({ ...base, exactSize: FILE_CHECKPOINT_MAX_FILE_SIZE + 1n })).toThrow(/size/u)
    expect(() => newFileCheckpointV1({ ...base, exactSize: 0n, backend: '\u0085test/native' })).toThrow(/backend/u)
    expect(() => newFileCheckpointV1({ ...base, exactSize: 0n, backend: '\ud800test/native' })).toThrow(/backend/u)
  })

  it('round-trips exact quarantine and retirement lifecycle evidence', () => {
    const base = {
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: 'file.bin',
      exactSize: 0n,
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      stateGeneration: 2n,
      checkpointGeneration: 0n,
      verifiedRanges: [],
      commitState: FILE_CHECKPOINT_COMMIT_VERIFIED,
    } as const
    const quarantined = newFileCheckpointV1({
      ...base,
      phase: FILE_CHECKPOINT_PHASE_QUARANTINED,
      quarantineReason: FILE_CHECKPOINT_QUARANTINE_STAGE_UNSAFE,
      quarantineOrigin: FILE_CHECKPOINT_ORIGIN_RETIRING,
      retirementReason: FILE_CHECKPOINT_RETIREMENT_INVALIDATED_REVISION,
    })
    expect(decodeFileCheckpointV1(encodeFileCheckpointV1(quarantined))).toEqual(quarantined)

    const retired = newFileCheckpointV1({
      ...base,
      phase: FILE_CHECKPOINT_PHASE_RETIRED,
      retirementReason: FILE_CHECKPOINT_RETIREMENT_INVALIDATED_REVISION,
    })
    expect(decodeFileCheckpointV1(encodeFileCheckpointV1(retired))).toEqual(retired)
  })

  it('rejects lifecycle claims that cannot describe a Go file-state history', () => {
    const base = {
      transferIntentDigest: intent,
      fileId,
      fileRevision: revision,
      canonicalPath: 'file.bin',
      exactSize: 0n,
      backend: 'test/native',
      rootIdentity: root,
      ownedOutputObject: object,
      stateGeneration: 2n,
      checkpointGeneration: 0n,
      verifiedRanges: [],
    } as const
    expect(() => newFileCheckpointV1({
      ...base,
      phase: FILE_CHECKPOINT_PHASE_ACTIVE,
      quarantineReason: FILE_CHECKPOINT_QUARANTINE_STAGE_UNSAFE,
    })).toThrow(/quarantine claims/u)
    expect(() => newFileCheckpointV1({
      ...base,
      phase: FILE_CHECKPOINT_PHASE_QUARANTINED,
      quarantineReason: FILE_CHECKPOINT_QUARANTINE_FINAL_MISMATCH,
      quarantineOrigin: FILE_CHECKPOINT_ORIGIN_PUBLISHED - 1,
    })).toThrow(/lifecycle claims/u)
    expect(() => newFileCheckpointV1({
      ...base,
      phase: FILE_CHECKPOINT_PHASE_RETIRED,
    })).toThrow(/retired lifecycle/u)
  })
})

function bytes(first: number, length: number): Uint8Array<ArrayBuffer> {
  return Uint8Array.from({ length }, (_, index) => (first + index) & 0xff) as Uint8Array<ArrayBuffer>
}
