import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const normalizationPath = resolve(
  repositoryRoot,
  'web/src/unicode/unicode-normalization-data.ts',
)
const caseFoldPath = resolve(repositoryRoot, 'web/src/unicode/unicode-case-fold-data.ts')
const outputPath = resolve(repositoryRoot, 'core/internal/unicode15/data_generated.go')

const normalizationSource = normalizedSource(normalizationPath)
const caseFoldSource = normalizedSource(caseFoldPath)
const unicodeVersion = quoted(normalizationSource, 'UNICODE_NORMALIZATION_VERSION')
if (quoted(caseFoldSource, 'UNICODE_CASE_FOLD_VERSION') !== unicodeVersion) {
  throw new Error('normalization and case-fold Unicode versions differ')
}
const generated = execFileSync('gofmt', {
  encoding: 'utf8',
  input: `// Code generated by scripts/unicode15/generate-go.mjs; DO NOT EDIT.

package unicode15

const (
	generatedUnicodeVersion = "${unicodeVersion}"
	normalizationDataSHA256 = "${quoted(normalizationSource, 'UNICODE_NORMALIZATION_DATA_SHA256')}"
	caseFoldSourceSHA256 = "${quoted(caseFoldSource, 'UNICODE_CASE_FOLD_SOURCE_SHA256')}"
	canonicalDecompositionData = \`${template(normalizationSource, 'UNICODE_CANONICAL_DECOMPOSITION_DATA')}\`
	combiningClassData = \`${template(normalizationSource, 'UNICODE_COMBINING_CLASS_DATA')}\`
	canonicalCompositionData = \`${template(normalizationSource, 'UNICODE_CANONICAL_COMPOSITION_DATA')}\`
	caseFoldData = \`${template(caseFoldSource, 'UNICODE_CASE_FOLD_DATA')}\`
)
`,
})

if (process.argv.includes('--check')) {
  if (normalizedSource(outputPath) !== generated) {
    throw new Error('core Unicode 15 data is stale; run go generate ./core/internal/unicode15')
  }
} else {
  writeFileSync(outputPath, generated, 'utf8')
}

function normalizedSource(path) {
  return readFileSync(path, 'utf8').replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}

function quoted(source, name) {
  const match = source.match(new RegExp(`^export const ${name} = '([^']+)' as const$`, 'mu'))
  if (match?.[1] === undefined) throw new Error(`missing quoted constant ${name}`)
  return match[1]
}

function template(source, name) {
  const prefix = `export const ${name} = \``
  const start = source.indexOf(prefix)
  const end = source.indexOf('`', start + prefix.length)
  if (start < 0 || end < 0) throw new Error(`missing template constant ${name}`)
  return source.slice(start + prefix.length, end)
}
